In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [26]:
X=df.drop('species',axis=1)
y=df['species']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
model_knn=KNeighborsClassifier(n_neighbors=5)

In [30]:
model_knn

KNeighborsClassifier()

In [31]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [32]:
model_knn.score(X_test,y_test)

0.98

In [33]:
from sklearn.svm import SVC

In [34]:
model_svm=SVC(C=10,kernel='rbf',gamma='auto')

In [35]:
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto')

In [36]:
model_svm.score(X_test,y_test)

1.0

In [37]:
#now lets use the gridSearch cv

In [38]:
from sklearn.model_selection import GridSearchCV

In [41]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
    
},cv=5,return_train_score=False)

In [42]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [43]:
classifier.cv_results_

{'mean_fit_time': array([0.00395651, 0.00493598, 0.00545673, 0.0028996 , 0.0057013 ,
        0.00469341, 0.00490184, 0.00463252]),
 'std_fit_time': array([9.34696161e-04, 3.36216119e-04, 1.45524786e-03, 2.44399554e-04,
        2.04239124e-03, 6.74009956e-05, 5.60289545e-05, 2.34953563e-04]),
 'mean_score_time': array([0.00336981, 0.00424366, 0.00359344, 0.00259948, 0.00407233,
        0.00364699, 0.00445414, 0.00368071]),
 'std_score_time': array([9.89799812e-04, 7.07254920e-04, 4.48886938e-04, 5.21580844e-04,
        2.43029525e-04, 8.09883173e-05, 1.31669749e-03, 1.59849087e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [44]:
results=pd.DataFrame(classifier.cv_results_)

In [45]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003957,0.000935,0.003370,0.000990,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004936,0.000336,0.004244,0.000707,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005457,0.001455,0.003593,0.000449,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002900,0.000244,0.002599,0.000522,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005701,0.002042,0.004072,0.000243,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004693,0.000067,0.003647,0.000081,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.004902,0.000056,0.004454,0.001317,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004633,0.000235,0.003681,0.000160,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [46]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [47]:
from sklearn.model_selection import RandomizedSearchCV

In [48]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
    
},n_iter=4,cv=5,return_train_score=False)

In [49]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [50]:
results=pd.DataFrame(classifier_r.cv_results_)

In [51]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003890,0.000654,0.003148,0.000539,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
1,0.003590,0.000812,0.002564,0.000467,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004667,0.001100,0.004637,0.002661,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
3,0.006186,0.002245,0.004300,0.000747,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [52]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1        1       linear         0.980000
2       30          rbf         0.960000
3       10          rbf         0.980000